### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by coagulant**
Adding python 3.3 support to waffle.

This PR continues our efforts after #96.
I've rebased necessary changes on top of py3k branch.

I've removed `smart_bytes` on after code review.

### CODE REVIEW

**Comment by jsocol** [comment]
Oh really, I never pushed a new release of jingo with py3 support? :-1: me. Let me do that and then we can pin to what will probably be v0.7.

**Comment by jsocol** [comment]
@coagulant I pushed jingo v0.7. Mind replacing the source requirement with that and squashing these down to one commit?

**Comment by coagulant** [comment]
Done. Is it ok to merge now? ;)

**Comment by jsocol** [comment]
Thanks Ilya! I'm going to cut a new release tonight.

**Comment by metamatik** [comment]
Hi James,

We — aka the oscaro.com team — are working on a new project using Python 3.3.
We would love to use waffle in it, and it looks like the port is basically done.
Would you say it's safe to start working with your py3k branch or should we wait for a proper release?

Thank you :)

**Comment by jsocol** [comment]
@metamatik I opened #113 and I'll try to sit down tonight and see what happens when I merge it, but if you want to run the py3k branch and report back that would be incredibly helpful!

**Comment by metamatik** [comment]
Thank you for your quick reply!
I am in France, so my day is basically over, but I'll try to test things a bit tomorrow at work.
We are in no emergency at all, our project is just getting started, so please don't go out of your way for us :)

**Pull request merged**
