### PR TITLE
Add SessionKV criteria to percentage based Flag

### PR DESCRIPTION
**Pull request by kew-l**

### CODE REVIEW

**Comment by willkg** [comment]
I don't understand what this is about. Is this related to an existing feature request in the issue tracker? If not, can you explain what problem you're trying to solve and why you're doing it this way?

**Comment by jsocol** [comment]
As always, [the roadmap](http://waffle.readthedocs.org/en/latest/about/roadmap.html) is subject to change if there's a really compelling +90% feature, but I'd also like to hear more about the motivation here. This behaves differently than other flag features, and has a number of implementation issues (frex, it could be done without adding new database tables at all).

**Comment by kew-l** [comment]
I need the percentage based Flag to only activate if additional select session key/value pairs match as well.

**Comment by jsocol** [comment]
This is just too far down the wrong road. Adding abstract base classes will allow this kind of customization in user-space, and that's the route forward from here.

**Pull request closed without merging**
