### PR TITLE
Add Django 1.7 compatibility

### PR DESCRIPTION
**Pull request by thoas**
Mention SOUTH_MIGRATION_MODULES settings in installation documentation
Add SOUTH_MIGRATION_MODULES settings in test_settings.py
Move old migrations directory to south_migrations dedicated directory
Update tox.ini to use Django 1.7 release
Add new migrations directory which contains the new schema

Don't hesitate if I need to rebase from your master after merging others PRs.

### CODE REVIEW

**Comment by jsocol** [comment]
Can you also add the new entries to `.travis.yml`? It doesn't use tox

**Comment by thoas** [comment]
done, let's wait for the build!

Oh I have missed the exclusion of Django 1.7 in Python 2.6

**Comment by thoas** [comment]
We are done @jsocol thank you for your contribution!

:beer:

**Comment by jsocol** [comment]
WOO! Awesome! Thank you so much @thoas!

**Pull request merged**
