### PR TITLE
South migration compatibility

### PR DESCRIPTION
**Pull request by nityaoberoi**
Added south migration files to the project

### CODE REVIEW

**Comment by jsocol** [comment]
3bf5115a89bbe73b2ab72fcae6c60e20c1bce337

Thanks! I may ask for help adding additional migrations in future versions

**Comment by nityaoberoi** [comment]
Anytime :)

**Comment by nityaoberoi** [comment]
Hi James,

Although you've accepted the pull request above, it doesnt seem to be reflected in the latest version of django-waffle (0.6) on pypi making it difficult for us to adapt to your latest version of the project (since we use south migrations). Any help would be apprecaited. Thanks

**Comment by jsocol** [comment]
Fixed in #8 (I think. We don't use South but it worked on my sqlite test db.)

**Comment by nityaoberoi** [comment]
Not sure why, but it still doesnt reflect on the pypi version:
http://pypi.python.org/pypi/django-waffle/0.7

It seems to be ignoring all new directories - migrations, tests, templates.

**Comment by jsocol** [comment]
Try now with 0.7.1. I switched to using find_packages instead of 
enumerating them.

On 4/20/2011 11:26 AM, nityaoberoi wrote:

> Not sure why, but it still doesnt reflect on the pypi version:
> http://pypi.python.org/pypi/django-waffle/0.7
> 
> It seems to be ignoring all new directories - migrations, tests, templates.
> 
> On Wed, Apr 20, 2011 at 10:58 AM, jsocol<
> reply@reply.github.com>wrote:
> 
> > Fixed in #8 (I think. We don't use South but it worked on my sqlite test
> > db.)
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jsocol/django-waffle/pull/6#issuecomment-1033227

## 

James Socol
Support Engineering Manager
Websmith
james@mozilla.com

**Comment by nityaoberoi** [comment]
Looks great! Thanks!

**Pull request closed without merging**
