### PR TITLE
Export all waffle settings in a separate file

### PR DESCRIPTION
**Pull request by thoas**
This PR introduces a new `waffle/settings.py` file to aggregate all default settings.

### CODE REVIEW

**Comment by thoas** [comment]
I'm waiting to add the two last PRs:
- Django 1.7 real compatibility
- Export signals to `models.py`

**Comment by jsocol** [comment]
:+1: I'm waiting on Travis but I'm going to tackle these basically in order so far. Let's make sure these are all stable then do the signals change, since that is required for 1.7 but not the other way around, and finally do 1.7 compat?

**Comment by thoas** [comment]
Travis is very slow fiou, I'm waiting for the merge to start working on signals then 1.7 compat as you said :+1:

**Comment by thoas** [comment]
tests passed yeah :tada:

**Comment by jsocol** [comment]
:ship:

**Comment by jsocol** [comment]
Ugh, except I can't automatically merge it. Mind rebasing? (Sorry)

**Comment by thoas** [comment]
done :+1:

**Comment by jsocol** [comment]
Aha! Here we go, failures!

I think the `@override_settings` + `reload(settings)` code path isn't a reliable way to do this. We could try rebasing again on top of #132 but maybe we should just use `mock.patch.object` on `waffle.settings` instead.

Also, would you mind undoing the merge commit and actually rebase it on top of master? It creates a much cleaner and easier to follow history.

**Comment by thoas** [comment]
done @jsocol with mock && rebase, let's wait for the travis result

**Comment by jsocol** [comment]
\o/ Woo!

**Pull request merged**
