### PR TITLE
Add support for Django 2.1

### PR DESCRIPTION
**Pull request by dbowring**
Add Django 2.1 to `tox.ini`. Tests pass without changes.

### CODE REVIEW

**Comment by dbowring** [comment]
These failures are caused by using postgres<9.4. I'm not familiar with travis-ci, but upgrading postgres should fix those errors.

**Comment by clintonb** [comment]
Yep. I just found https://groups.google.com/forum/#!topic/django-users/behDaxyzVE8.

**Comment by clintonb** [comment]
Try adding this to `.travsi.yml`:

```yaml
addons:
  postgresql: 9.4
```

https://docs.travis-ci.com/user/database-setup/#using-a-different-postgresql-version

**Comment by clintonb** [comment]
Would you also update `setup.py`, please?

https://github.com/django-waffle/django-waffle/blob/master/setup.py#L25

**Review by clintonb — APPROVED** [review]

**Pull request merged**
