### PR TITLE
Updated management commands for compatibility with Django 1.10

### LINKED ISSUE #199: Django 1.10's BaseCommand no longer has option_list.
./manage.py waffle_switch --help

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File ".pyenv/versions/project/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File ".pyenv/versions/project/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".pyenv/versions/project/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File ".pyenv/versions/project/lib/python3.5/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File ".pyenv/versions/3.5.1/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File ".pyenv/versions/project/lib/python3.5/site-packages/waffle/management/commands/waffle_switch.py", line 10, in <module>
    class Command(BaseCommand):
  File ".pyenv/versions/project/lib/python3.5/site-packages/waffle/management/commands/waffle_switch.py", line 11, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

### PR DESCRIPTION
**Pull request by clintonb**
The management commands are now compatible with Django 1.8+. This was achieved by replacing the usage of option_list with add_arguments(). Additionally, unit tests have been added for the commands.

Fixes #199

### CODE REVIEW

**Comment by clintonb** [comment]
@jsocol @thallada please review

**Comment by tednology** [comment]
I was just thinking about writing a similar PR, thanks @clintonb!

**Comment by clintonb** [comment]
@jsocol @thallada please review

**Review by thallada — APPROVED** [review]
It looks like this PR fixes the same issue as #236 does, but it has tests :1st_place_medal:. I tested your branch out, and I'm now able to use the management commands in Django 1.11.

The only nitpicky thing I'll mention is that there's a few lines here over 80 chars long and that's inconsistent with the rest of the code base which seems to keep it under 80 chars.

**Pull request merged**
