### PR TITLE
Added language support to flags

### PR DESCRIPTION
**Pull request by fgaudin**
To enable releasing new features only for languages which are up to date

### CODE REVIEW

**Comment by jsocol** [comment]
I really want to merge this but is `request.LANGUAGE_CODE` standard? At Mozilla we are using `request.locale`. If we're wrong, we're wrong and should switch, but I don't see anything in [the docs](https://docs.djangoproject.com/en/1.4/ref/request-response/#django.http.HttpRequest).

If there's not a standard, we might need a waffle setting to pick the `request` attribute to use here.

**Comment by fgaudin** [comment]
just before this paragraph https://docs.djangoproject.com/en/1.3/topics/i18n/deployment/#how-django-discovers-translations

"Once LocaleMiddleware determines the user's preference, it makes this preference available as request.LANGUAGE_CODE for each HttpRequest. Feel free to read this value in your view code."

**Comment by jsocol** [comment]
Fair enough, we should update our locale middleware to use `LANGUAGE_CODE` instead of `locale`, based on that.

**Comment by jsocol** [comment]
7471bcbcaea2b105e4cf942c0b663f2540511dfc Thanks!

**Comment by unho** [comment]
Please update the docs. There is no reference to this new field on http://waffle.readthedocs.org/en/latest/types.html#flags

**Pull request closed without merging**
