### PR TITLE
handle WAFFLE_SUFFIX

### PR DESCRIPTION
**Pull request by washort**

### CODE REVIEW

**Comment by jsocol** [comment]
Can you rebase this onto master/0.8.0? It's based on an older version right now.

**Comment by kumar303** [comment]
@washort can you rebase and sync this up? It's out of date with master and I'd like to get some new waffle changes from master into Zamboni.

**Comment by washort** [comment]
Updated.

**Comment by jezdez** [comment]
This is most definitely the wrong way to solve this. Please use a database router in your Django project, that allows you to point Django at a different table just for the waffle app. See https://docs.djangoproject.com/en/1.5/topics/db/multi-db/#an-example for more information.

**Comment by jsocol** [comment]
Aha! Thanks @jezdez, I never liked this approach.

**Pull request closed without merging**
