### PR TITLE
Test all pull requests for docs

### PR DESCRIPTION
**Pull request by dancergraham**
This workflow runs against all PRs to catch problems with docs. It catches any problems before merging to master. 

Related to #526

  update the CI workflow to include a documentation build stage.

### CODE REVIEW

**Review by clintonb — COMMENTED** [review]
This should be done for pull requests that touch docs. Finding a failure after merging to master is too late. Can you add a workflow that runs against PRs?

**Comment by dancergraham** [comment]
> This should be done for pull requests that touch docs. Finding a failure after merging to master is too late. Can you add a workflow that runs against PRs?

Hello, this workflow runs against both PRs and on merge - see here 
https://github.com/jazzband/django-waffle/actions/runs/12074017053/job/33671235325?pr=536

**Comment by dancergraham** [comment]
@clintonb could you look again please - I think this PR already does what you are asking for:

* Without this PR doc building can fail silently on readthedocs.io - the only visible sign will be the new status badge on the readme
* With this PR the CI will fail before merging if the docs do not build correctly

**Comment by dancergraham** [comment]
Hi @clintonb I still think this PR does exactly what you are asking for - can you please rephrase if I'm missing something?

**Review by clintonb — APPROVED** [review]

**Pull request merged**
