### PR TITLE
Add classed based views mixins

### LINKED ISSUE #287: Create mixins for class based views to replace the decorators
Create `WaffleFlagViewMixin` and a `WaffleSwitchViewMixin` to use in class based views intead of the available decorators.

### PR DESCRIPTION
**Pull request by hugobessa**
This creates class based views mixins for flags and switches using the decorators already defined by package to avoid duplication of the logic.

The mixins support two attruibutes:

* flag_name (string)
* inactive_flag_redirect_to (string)

And it also defines methods to fetch these attributes, to make easy to change the behavior depending on the request.

fixes #287

### CODE REVIEW

**Comment by hugobessa** [comment]
@jsocol can you remove the stale label, please?

**Comment by hugobessa** [comment]
oh, the bot did it automatically, sorry to bother you

**Comment by hugobessa** [comment]
@jsocol is this still relevant? If so, please reopen

**Comment by cymig** [comment]
Hi there,

I'm planning to use waffle with one of my projects. 

Is it plan to support a way to decorate an entire BaseView like TemplateView or support classed based views mixins ?

Thanks

**Comment by clintonb** [comment]
@cymig I have no immediate plans to support this functionality. This issue was closed prior to my assuming stewardship of this project. Would the code in this PR meet your needs?

**Comment by cymig** [comment]
Thanks for your reply @clintonb . I'll start playing around with this PR and see if that fully meets my needs.

**Pull request closed without merging**
