### PR TITLE
Make middleware compatible with Django 1.10.

### PR DESCRIPTION
**Pull request by aaugustin**

### CODE REVIEW

**Comment by jsocol** [comment]
Thanks!

**Comment by aaugustin** [comment]
Hello James, I noticed you've been too busy to make a release since I contributed this patch.

This has caused several other people to hit the same problem (#241, #240, #232) and, mostly likely, they reverted to the old-style MIDDLEWARE_CLASSES setting, which isn't a great outcome.

If there anything I can do to help — including making that release and dealing with the downfall if there are issues — let me know. I can also do a bit of triage in open issues if that makes you more comfortable before pushing a release.

**Comment by aarcro** [comment]
Need to get this in a release please

**Comment by aarcro** [comment]
To use the released code, just add the mixin yourself, and use your own subclass, stick it in middleware.py in one of your apps.

```python
from django.utils.deprecation import MiddlewareMixin
from waffle.middleware import WaffleMiddleware as BaseWaffleMiddleware


class WaffleMiddleware(BaseWaffleMiddleware, MiddlewareMixin):
    """Make WaffleMiddleware new Django 1.10 style compatible"""
    pass

```

**Pull request merged**
